# vim:ft=kitty

## name: Nord Monochrome
## author:
## license: MIT
## upstream:
## blurb: Nord Monochrome theme based on https://zed-themes.com/themes/XWqaW0xl0WJSJKP-zJsNi?name=Monochrome%20Zed

foreground                      #eeffff
background                      #1a1a1a
selection_foreground            #eeffff
selection_background            #5e81ac

cursor                          #eeffff
cursor_text_color               #eeffff

url_color                       #81a1c1

active_border_color             #81a1c1
inactive_border_color           #424242
bell_border_color               #81a1c1
visual_bell_color               none

wayland_titlebar_color          system
macos_titlebar_color            system

active_tab_background           #424242
active_tab_foreground           #eeffff
inactive_tab_background         #1a1a1a
inactive_tab_foreground         #eeffff
tab_bar_background              #1a1a1a
tab_bar_margin_color            none

mark1_foreground                #eeffff
mark1_background                #212121
mark2_foreground                #eeffff
mark2_background                #212121
mark3_foreground                #eeffff
mark3_background                #212121

#: black
color0                          #1a1a1a
color8                          #1a1a1a

#: red
color1                          #bf616a
color9                          #bf616a

#: green
color2                          #a3be8c
color10                         #a3be8c

#: yellow
color3                          #ebcb8b
color11                         #ebcb8b

#: blue
color4                          #88c0d0
color12                         #88c0d0

#: magenta
color5                          #b48ead
color13                         #b48ead

#: cyan
color6                          #8fbcbb
color14                         #8fbcbb

#: white
color7                          #eeffff
color15                         #eeffff
